name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Start Docker
      run: docker compose up -d --build

    - name: Wait for container to start
      run: sleep 3

    - name: Verify site is reachable
      run: curl --fail http://localhost:3000

    - name: Show running containers
      run: docker compose ps

    - name: Show Docker logs if fail
      if: failure()
      run: docker compose logs

    - name: Shutdown Docker
      if: always()
      run: docker compose down